kind: Pod
apiVersion: v1
metadata:
  generateName: rosa-project-git-857785bcf8-
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.0.116/23"],"mac_address":"0a:58:0a:80:00:74","gateway_ips":["10.128.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.0.1"}],"ip_address":"10.128.0.116/23","gateway_ip":"10.128.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.0.116"
          ],
          "mac": "0a:58:0a:80:00:74",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    openshift.openshift.io/restartedAt: '2024-04-28T18:17:04.771Z'
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '3109915'
  name: rosa-project-git-857785bcf8-t5r9k
  uid: 1baa68e2-156b-44e6-8514-032ddf688a63
  creationTimestamp: '2024-04-30T01:45:50Z'
  managedFields:
    - manager: ip-10-0-131-189
      operation: Update
      apiVersion: v1
      time: '2024-04-30T01:45:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.ovn.org/pod-networks': {}
      subresource: status
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-04-30T01:45:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.openshift.io/restartedAt': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deployment': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"c7e46347-d835-4f82-ba8c-8a5596f860c7"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"rosa-project-git"}':
              'f:envFrom': {}
              'f:image': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
                'k:{"containerPort":8443,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: multus-daemon
      operation: Update
      apiVersion: v1
      time: '2024-04-30T01:45:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2024-05-02T15:41:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.128.0.116"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: rosa-project
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: rosa-project-git-857785bcf8
      uid: c7e46347-d835-4f82-ba8c-8a5596f860c7
      controller: true
      blockOwnerDeletion: true
  labels:
    app: rosa-project-git
    deployment: rosa-project-git
    pod-template-hash: 857785bcf8
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-44tbp
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-131-189.ec2.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c7'
    fsGroup: 1000770000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: rosa-project-git
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000770000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: kube-api-access-fhxqx
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      envFrom:
        - secretRef:
            name: mysql
      image: 'image-registry.openshift-image-registry.svc:5000/rosa-project/rosa-project-git@sha256:03f2df79c3592d21eff8e4a4e5f4079769a871408f5c7453074e97af3e20300e'
  serviceAccount: default
  volumes:
    - name: kube-api-access-fhxqx
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-04-30T01:45:50Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-04-30T01:45:51Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-04-30T01:45:51Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-04-30T01:45:50Z'
  hostIP: 10.0.131.189
  podIP: 10.128.0.116
  podIPs:
    - ip: 10.128.0.116
  startTime: '2024-04-30T01:45:50Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: rosa-project-git
      state:
        running:
          startedAt: '2024-04-30T01:45:51Z'
      imageID: 'image-registry.openshift-image-registry.svc:5000/rosa-project/rosa-project-git@sha256:03f2df79c3592d21eff8e4a4e5f4079769a871408f5c7453074e97af3e20300e'
      image: 'image-registry.openshift-image-registry.svc:5000/rosa-project/rosa-project-git@sha256:03f2df79c3592d21eff8e4a4e5f4079769a871408f5c7453074e97af3e20300e'
      lastState: {}
      containerID: 'cri-o://d1e71a5ed903937dcebe7d8bcc56a0e15845ffc1bf43c3f76123cab197846434'
  qosClass: BestEffort
