apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  creationTimestamp: '2024-04-30T20:22:33Z'
  generation: 1
  managedFields:
    - apiVersion: monitoring.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:groups':
            .: {}
            'k:{"name":"workernodealerts"}':
              .: {}
              'f:name': {}
              'f:rules': {}
      manager: Mozilla
      operation: Update
      time: '2024-04-30T20:22:33Z'
  name: workernodealerts
  namespace: rosa-project
  resourceVersion: '2645174'
  uid: ef7daf67-b279-4eca-9fff-f0ad7c610259
spec:
  groups:
    - name: workernodealerts
      rules:
        - alert: WorkerNodeCountIncrease
          expr: 'changes(node_namespace_pod:kube_pod_info:node_name[1h]) > 0'
          for: 1m

